### ISSUE TITLE
All Strings Not Translated

### ISSUE THREAD

**Issue by devinsays** [devinsays/instant-content#2]
There are a number of strings not translated.  I don't think this is an issue- as we are not planning to localize the plugin at this time.

**Comment by devinsays** [comment]
This was taken care of in: https://github.com/devinsays/instant-content/pull/4/files#r7235696

**Comment by GaryJones** [comment]
If any were missed, they will be relatively simple "one-off" fixes, rather than an afternoon spent tracking them all down.

> I don't think this is an issue- as we are not planning to localize the plugin at this time.

Just to be a little picky here - while the developers may not be planning to localize the plugin (and nor should they be), foreign language users may wish to localize it so they can use this plugin comfortably - and that's only possible if the developers internationalize it (which is what this ticket refers to).

**Comment by devinsays** [comment]
Agreed.  Glad this was done.

**Comment by GaryJones** [comment]
This can be closed I think.
